version: 0.1
http:
  addr: 0.0.0.0:5000
  secret: secret
  debug:
    addr: 0.0.0.0:5001
log:
  level: info
storage:
  filesystem:
    rootdirectory: /registry
  delete:
    enabled: true
auth:
  token:
    realm: token  
    service: container_registry
    issuer: gitlab-issuer
    rootcertbundle: /certs/registry-auth.crt

