version: '2'
services:
  redis_git:
    image: redis:3.0-alpine
    container_name: redis-git
    hostname: redis-git
    network_mode: "host"
    command:
    - --maxmemory 256mb
    - --maxmemory-policy volatile-lru 
    - --bind 0.0.0.0

  postgresql:
    image: postgres:9.6.1-alpine
    network_mode: "host"
    container_name: postgres-git
    environment:
    - POSTGRES_USER=gitlab
    - POSTGRES_PASSWORD=Pa$sgit1324
    - POSTGRES_DB=gitlab

  gitlab:
    image: gitlab/gitlab-ce:8.16.2-ce.0
    container_name: gitlab
    privileged: true
    depends_on:
    - redis_git
    - postgresql
    network_mode: "host"
    volumes:
    - ./gitlab/gitlab/etc/:/opt/gitlab/etc/
    - ./registry:/registry
    - ./certs:/certs
  registry-clients:
    image: registry:2
    network_mode: "host"
    container_name: registry-clients
    privileged: true
    depends_on:
    - redis_git
    - postgresql
    - gitlab
    volumes:
        - ./registry:/registry
        - ./certs:/certs
        - ./auth/htpasswd:/auth/htpasswd
        - ./registry/config-client.yml:/etc/docker/registry/config.yml
  registry:
    image: registry:2
    network_mode: "host"
    container_name: registry
    privileged: true
    depends_on:
    - redis_git
    - postgresql
    - gitlab
    - registry-clients
    volumes:
        - ./registry:/registry
        - ./certs:/certs
        - ./auth/htpasswd:/auth/htpasswd
        - ./registry/config.yml:/etc/docker/registry/config.yml
  memcached-app:
    image: memcached:1.4-alpine
    depends_on:
    - redis_git
    - postgresql
    - gitlab
    - registry-clients
    - registry
    ports:
        - "11211:11211"
    container_name: memcached_for_application
  cadvisor:
    image: google/cadvisor
    depends_on:
    - redis_git
    - postgresql
    - gitlab
    - registry-clients
    - registry
    - memcached-app
    ports:
        - "8099:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
  dev_application:
    depends_on:
    - redis_git
    - postgresql
    - gitlab
    - registry-clients
    - registry
    - cadvisor
    - memcached-app
    image: onyxet/englishdom:7.1-app_1
    container_name: development_app
    hostname: development_app
    ports:
    - '80:8086'
    environment:
    - UWSGI_SHOW-CONFIG=true
    - UWSGI_CHECK-STATIC=/opt
    - UWSGI_STATIC-INDEX=index.html
    - UWSGI_PHP-INDEX=index.php
    - UWSGI_PHP-DOCROOT=/opt
    - UWSGI_PHP-SAPI-NAME=apache
    - UWSGI_HTTP=:8086
    - UWSGI_HTTP_MODIFIER1=14
    - UWSGI_LISTEN=50
    - UWSGI_MASTER-FIFO=/tmp/fifo0
    - UWSGI_HTTP-TIMEOUT=90
    - UWSGI_HTTP-CONNECT-TIMEOUT=5
    - UWSGI_MASTER=TRUE
    - UWSGI_PROJECT_ROOT_DIR=/opt
    - UWSGI_CHDIR=/opt
    - UWSGI_WORKERS=4
    - UWSGI_OFFLOAD_THREADS=8
    - UWSGI_VACUUM=true






